CREATE TABLE licenciaturas(
   clave_lic    INTEGER  NOT NULL PRIMARY KEY 
  ,licenciatura VARCHAR(59) NOT NULL
);
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (9,'FÍSICO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (50,'LICENCIADO EN INFORMÁTICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (24,'LICENCIADO EN ACTIVIDAD FÍSICA Y DEPORTE');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (40,'LICENCIADO EN DOCENCIA DE LA LENGUA Y LITERATURA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (95,'INGENIERÍA INDUSTRIAL');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (5,'CIRUJANO DENTISTA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (86,'INGENIERIA ELECTRONICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (2,'BIOINGENIERIA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (20,'INGENIERO MECÁNICO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (68,'NONATECNOLOGÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (10,'INGENIERO AEROESPACIAL');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (17,'INGENIERO EN MECATRÓNICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (88,'INGENIERIA EN SISTEMAS COMPUTACIONALES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (80,'EDUCACIÓN PREESCOLAR');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (54,'LICENCIADO EN MERCADOTECNIA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (88,'INGENIERIA ELECTROMECANICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (97,'COMERCIO EXTERIOR Y ADUANAS');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (56,'LICENCIADO EN NEGOCIOS INTERNACIONALES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (42,'LICENCIADO EN DOCENCIA DE LA MATEMÁTICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (70,'QUÍMICO FARMACOBIÓLOGO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (25,'LICENCIADO EN ADMINISTRACIÓN DE EMPRESAS');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (57,'LICENCIADO EN PSICOLOGÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (34,'LICENCIADO EN CONTADURÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (1,'ARQUITECTO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (69,'OCEANÓLOGO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (28,'LICENCIADO EN ASESORÍA PSICOPEDAGÓGICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (65,'MÉDICO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (39,'LICENCIADO EN DOCENCIA DE IDIOMAS');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (87,'INGENIERIA MECATRONICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (37,'LICENCIADO EN DISEÑO GRÁFICO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (96,'INGENIERÍA EN TECNOLOGÍA DE LA MANUFACTURA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (32,'LICENCIADO EN CIENCIAS DE LA EDUCACIÓN');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (49,'LICENCIADO EN HISTORIA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (19,'INGENIERO INDUSTRIAL');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (13,'INGENIERO CIVIL');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (52,'LICENCIADO EN MATEMÁTICAS APLICADAS');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (58,'LICENCIADO EN RELACIONES INTERNACIONALES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (11,'INGENIERO AGRÓNOMO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (85,'LICENCIADO EN DERECHO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (45,'LICENCIADO EN ENFERMERÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (15,'INGENIERO EN COMPUTACIÓN');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (92,'NEGOCIOS');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (99,'INGENIERA MECATRÓNICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (48,'LICENCIADO EN GESTIÓN TURÍSTICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (98,'PSICOLOGÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (60,'LICENCIADO EN SOCIOLOGÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (90,'INGENIERÍA EN SISTEMAS COMPUTACIONALES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (82,'CRIMINALÍSTICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (66,'MÉDICO VETERINARIO ZOOTECNISTA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (81,'INGENIERÍA CIBERNÉTICA ELECTRÓNICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (84,'PSICOLOGÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (18,'INGENIERO ENERGIAS RENOVABLES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (71,'QUÍMICO INDUSTRIAL');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (83,'EDUCACIÓN');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (44,'LICENCIADO EN ECONOMÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (30,'LICENCIADO EN CIENCIAS COMPUTACIONALES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (4,'BIOTECNÓLOGO EN ACUACULTURA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (16,'INGENIERO EN ELECTRÓNICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (36,'LICENCIADO EN DERECHO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (93,'INGENIERIA EN NANOTECNOLOGIA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (3,'BIÓLOGO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (91,'INGENIERIA MECANICA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (31,'LICENCIADO EN CIENCIAS DE LA COMUNICACIÓN');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (89,'INGENIERÍA INDUSTRIAL');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (29,'LICENCIADO EN CIENCIAS AMBIENTALES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (94,'INGENIERIA EN CIENCIAS COMPUTACIONALES Y TELECOMUNICACIONES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (98,'PSICOLOGIA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (97,'INGENIERÍA EN ENERGÍAS RENOVABLES');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (47,'LICENCIADO EN GASTRONOMÍA');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (64,'LICENCIADO EN TURISMO');
INSERT INTO licenciaturas(clave_lic,licenciatura) VALUES (59,'LICENCIADO EN SISTEMAS COMPUTACIONALES');
