CREATE TABLE unidades(
   clave_uni  INTEGER  NOT NULL
  ,num_unidad INTEGER  NOT NULL  PRIMARY KEY 
  ,unidad     VARCHAR(59) NOT NULL
  ,campus     INTEGER  NOT NULL
);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,400,'FACULTAD DE CIENCIAS',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,103,'FACULTAD DE CIENCIAS ADMINISTRATIVAS',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,340,'ESCUELA DE DEPORTES (TIJUANA)',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,108,'FACULTAD DE PEDAGOGIA E INNOVACION EDUCATIVA',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (13,1,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,107,'FACULTAD DE ODONTOLOGIA',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,50,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,402,'FACULTAD DE INGENIERIA, ARQUITECTURA Y DISEÑO',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,301,'FACULTAD DE CONTADURIA Y ADMINISTRACION',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,351,'CENTRO DE INGENIERIA Y TECNOLOGIA VALLE DE LAS PALMAS CITEC',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,105,'FACULTAD DE INGENIERIA',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,51,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (25,52,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,53,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,306,'FACULTAD DE TURISMO Y MERCADOTECNIA',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,54,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (7,55,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,300,'FACULTAD DE CIENCIAS QUIMICAS  E INGENIERIA',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,350,'CENTRO DE CIENCIAS DE LA SALUD VALLE DE LAS PALMAS CISALUD',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,430,'FACULTAD DE INGENIERIA Y NEGOCIOS SAN QUINTIN',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,401,'FACULTAD DE CIENCIAS MARINAS',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,56,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (25,57,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,304,'FACULTAD DE MEDICINA Y PSICOLOGIA(TIJUANA)',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,419,'FACULTAD DE IDIOMAS (ENSENADA)',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,58,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,59,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,414,'FACULTAD DE CIENCIAS ADMINISTRATIVAS Y SOCIALES',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,326,'FACULTAD DE HUMANIDADES (TIJUANA)',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,106,'FACULTAD  DE MEDICINA',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,100,'FACULTAD DE ARQUITECTURA Y DISENO',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (25,60,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,61,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,102,'FACULTAD DE CIENCIAS SOCIALES Y POLITICAS',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (25,62,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,63,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,64,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,65,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,66,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,67,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,68,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (8,69,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,439,'ESCUELA DE CIENCIAS DE LA SALUD (ENSENADA)',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,70,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,71,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,72,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (12,73,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,149,'ESCUELA DE DEPORTES (MEXICALI)',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,115,'FACULTAD DE IDIOMAS (MEXICALI)',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,431,'ESCUELA DE DEPORTES (ENSENADA)',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (7,74,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (7,75,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,76,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,77,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (6,78,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,201,'INSTITUTO DE INVESTIGACIONES EN CIENCIAS VETERINARIAS',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (1,79,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (6,80,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (7,81,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (6,82,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (13,83,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,303,'FACULTAD DE ECONOMIA Y RELACIONES INTERNACIONALES',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,84,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (1,85,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (7,86,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,87,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,88,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,2,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,3,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,101,'FACULTAD DE CIENCIAS HUMANAS',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,4,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,5,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,200,'INSTITUTO DE CIENCIAS AGRICOLAS',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (6,6,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,7,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (2,8,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (2,9,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,10,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (25,11,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,12,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,109,'FACULTAD DE ENFERMERIA',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (13,13,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,14,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,15,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,16,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,17,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,18,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (2,19,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,20,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,21,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,22,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,23,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,24,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (13,25,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,26,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (3,27,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,28,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,29,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (6,30,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (13,31,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,32,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,33,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (7,34,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,35,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (2,36,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,37,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (6,38,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (2,39,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,40,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,41,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (25,42,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (25,43,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,44,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (12,45,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (6,46,'N/A',2);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,440,'ESCUELA DE ENOLOGIA Y GASTRONOMIA',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,47,'N/A',1);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (11,104,'FACULTAD DE DERECHO',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (10,48,'N/A',3);
INSERT INTO unidades(clave_uni,num_unidad,unidad,campus) VALUES (4,49,'N/A',1);
