CREATE TABLE unidades(
   num_unidad INTEGER  NOT NULL PRIMARY KEY 
  ,unidad     VARCHAR(59) NOT NULL
);
INSERT INTO unidades(num_unidad,unidad) VALUES (400,'FACULTAD DE CIENCIAS');
INSERT INTO unidades(num_unidad,unidad) VALUES (103,'FACULTAD DE CIENCIAS ADMINISTRATIVAS');
INSERT INTO unidades(num_unidad,unidad) VALUES (340,'ESCUELA DE DEPORTES (TIJUANA)');
INSERT INTO unidades(num_unidad,unidad) VALUES (108,'FACULTAD DE PEDAGOGIA E INNOVACION EDUCATIVA');
INSERT INTO unidades(num_unidad,unidad) VALUES (1,'N/A');
INSERT INTO unidades(num_unidad,unidad) VALUES (107,'FACULTAD DE ODONTOLOGIA');
INSERT INTO unidades(num_unidad,unidad) VALUES (402,'FACULTAD DE INGENIERIA, ARQUITECTURA Y DISEÑO');
INSERT INTO unidades(num_unidad,unidad) VALUES (301,'FACULTAD DE CONTADURIA Y ADMINISTRACION');
INSERT INTO unidades(num_unidad,unidad) VALUES (351,'CENTRO DE INGENIERIA Y TECNOLOGIA VALLE DE LAS PALMAS CITEC');
INSERT INTO unidades(num_unidad,unidad) VALUES (105,'FACULTAD DE INGENIERIA');
INSERT INTO unidades(num_unidad,unidad) VALUES (306,'FACULTAD DE TURISMO Y MERCADOTECNIA');
INSERT INTO unidades(num_unidad,unidad) VALUES (300,'FACULTAD DE CIENCIAS QUIMICAS  E INGENIERIA');
INSERT INTO unidades(num_unidad,unidad) VALUES (350,'CENTRO DE CIENCIAS DE LA SALUD VALLE DE LAS PALMAS CISALUD');
INSERT INTO unidades(num_unidad,unidad) VALUES (430,'FACULTAD DE INGENIERIA Y NEGOCIOS SAN QUINTIN');
INSERT INTO unidades(num_unidad,unidad) VALUES (401,'FACULTAD DE CIENCIAS MARINAS');
INSERT INTO unidades(num_unidad,unidad) VALUES (304,'FACULTAD DE MEDICINA Y PSICOLOGIA(TIJUANA)');
INSERT INTO unidades(num_unidad,unidad) VALUES (419,'FACULTAD DE IDIOMAS (ENSENADA)');
INSERT INTO unidades(num_unidad,unidad) VALUES (414,'FACULTAD DE CIENCIAS ADMINISTRATIVAS Y SOCIALES');
INSERT INTO unidades(num_unidad,unidad) VALUES (326,'FACULTAD DE HUMANIDADES (TIJUANA)');
INSERT INTO unidades(num_unidad,unidad) VALUES (106,'FACULTAD  DE MEDICINA');
INSERT INTO unidades(num_unidad,unidad) VALUES (100,'FACULTAD DE ARQUITECTURA Y DISENO');
INSERT INTO unidades(num_unidad,unidad) VALUES (102,'FACULTAD DE CIENCIAS SOCIALES Y POLITICAS');
INSERT INTO unidades(num_unidad,unidad) VALUES (439,'ESCUELA DE CIENCIAS DE LA SALUD (ENSENADA)');
INSERT INTO unidades(num_unidad,unidad) VALUES (149,'ESCUELA DE DEPORTES (MEXICALI)');
INSERT INTO unidades(num_unidad,unidad) VALUES (115,'FACULTAD DE IDIOMAS (MEXICALI)');
INSERT INTO unidades(num_unidad,unidad) VALUES (431,'ESCUELA DE DEPORTES (ENSENADA)');
INSERT INTO unidades(num_unidad,unidad) VALUES (201,'INSTITUTO DE INVESTIGACIONES EN CIENCIAS VETERINARIAS');
INSERT INTO unidades(num_unidad,unidad) VALUES (303,'FACULTAD DE ECONOMIA Y RELACIONES INTERNACIONALES');
INSERT INTO unidades(num_unidad,unidad) VALUES (101,'FACULTAD DE CIENCIAS HUMANAS');
INSERT INTO unidades(num_unidad,unidad) VALUES (200,'INSTITUTO DE CIENCIAS AGRICOLAS');
INSERT INTO unidades(num_unidad,unidad) VALUES (109,'FACULTAD DE ENFERMERIA');
INSERT INTO unidades(num_unidad,unidad) VALUES (440,'ESCUELA DE ENOLOGIA Y GASTRONOMIA');
INSERT INTO unidades(num_unidad,unidad) VALUES (104,'FACULTAD DE DERECHO');
