(require "test.lisp")
(defun permute (lst)
  (if 
    (null lst) 
    '(()) 
     (mapcan #'(lambda (head)
	           (loop for next in (permute (remove head lst))
  		   	collect (cons head next)
		   )
	       ) 
	     lst
     )
  )
)
(test #'permute  '(1 2 3) '((1 2 3) (1 3 2) (2 3 1) (2 1 3) (3 1 2) (3 2 1)))
